# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "PRGRJIF-XS88113.snowflakecomputing.com"
user = "RAVIP"
password = "8JNHM8yu2ApC8pg"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
